name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      firebase:
        image: andreysenov/firebase-tools
        ports:
          - 4000:4000
          - 9099:9099
          - 8080:8080
          - 9199:9199
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        options: >-
          --health-cmd "curl -f http://localhost:4000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: make test
      env:
        FIREBASE_EMULATOR_HOST: localhost:8080

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: elitecode
        path: elitecode

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Create release directory
      run: mkdir -p dist

    - name: Build releases
      run: make release

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/elitecode-linux-amd64.tar.gz
          dist/elitecode-darwin-amd64.tar.gz
          dist/elitecode-darwin-arm64.tar.gz
          dist/elitecode-windows-amd64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 